import {readAccountFile} from './xlsx-account.mjs';
import {loadPrivate,savePrivate,clearPrivate,marketURL} from './api-client.mjs';
const $=id=>document.getElementById(id),status=message=>$('importStatus').textContent=message;
function flows(){return $('externalFlows').value.split(/\r?\n/).filter(x=>x.trim()).map(line=>{const [date,value,...extra]=line.trim().split(/[\s,]+/),amount=Number(value);if(extra.length||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(amount))throw Error('金流請填「日期 金額」，轉出用負數');return {date,amount};});}
async function validateComparison(data){const response=await fetch(marketURL,{cache:'no-store'});if(!response.ok)throw Error('無法取得公開行情，尚未儲存匯入資料');const {rows}=await response.json();const {buildComparison}=await import('./comparison-core.mjs');return buildComparison({market:rows,account:{...data.account,externalFlows:data.externalFlows},balances:data.balances,initialCash:data.initialCash});}
function populate(data){if(!data)return;$('initialCash').value=data.initialCash;$('externalFlows').value=data.externalFlows.map(f=>f.date+' '+f.amount).join('\n');status('私人帳戶保存在此瀏覽器｜Excel快照 '+data.account.asOf);}
function applyAccount(data){const a=data.account;for(const [id,value]of Object.entries({shares:a.shares,cash:a.cash,reserved:a.reserve,feeRate:100*(a.fees?.buy??.001425),sellFeeRate:100*(a.fees?.sell??.001425),sellTax:100*(a.fees?.tax??.001)})){if($(id)){$(id).value=value;$(id).dispatchEvent(new Event('input'));}}$('save').click();$('refresh').click();}
export function mountImport(){
 populate(loadPrivate());
 $('workbookFile').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;status('正在瀏覽器內讀取Excel…');try{const account=await readAccountFile(file),old=loadPrivate(),initialCash=Number($('initialCash').value);if(!Number.isFinite(initialCash)||initialCash<0)throw Error('請填6/1投資現金');const map=new Map((old?.balances??[]).map(b=>[b.date,b]));map.set(account.asOf,{date:account.asOf,cash:account.cash,shares:account.shares,savedAt:account.savedAt});const data={format:'etf-private-backup-v1',account,initialCash,externalFlows:flows(),balances:[...map.values()].sort((a,b)=>a.date.localeCompare(b.date))};await validateComparison(data);savePrivate(data);populate(data);applyAccount(data);status('Excel匯入完成，資料只保存在此瀏覽器。');}catch(e){status('匯入未完成：'+e.message);}finally{event.target.value='';}});
 $('backupFile').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>4*1024*1024)throw Error('備份檔案過大');const data=JSON.parse(await file.text());await validateComparison(data);savePrivate(data);populate(data);applyAccount(data);}catch(e){status('備份匯入未完成：'+e.message);}finally{event.target.value='';}});
 $('exportPrivate').addEventListener('click',()=>{const data=loadPrivate();if(!data){status('請先匯入帳戶');return;}data.exposureSettings=JSON.parse(localStorage.getItem('00631L-exposure-online-v1')||'null');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='私人帳戶備份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 $('saveFlows').addEventListener('click',async()=>{try{const data=loadPrivate();if(!data)throw Error('請先匯入帳戶');const updated={...data,initialCash:Number($('initialCash').value),externalFlows:flows()};await validateComparison(updated);savePrivate(updated);$('refresh').click();status('起始現金與外部金流已更新，只保存在此瀏覽器。');}catch(e){status(e.message);}});
 $('erasePrivate').addEventListener('click',()=>{if(confirm('清除此瀏覽器的帳戶與持倉設定？請先匯出備份。')){clearPrivate();localStorage.removeItem('00631L-exposure-online-v1');location.reload();}});
 window.addEventListener('load',()=>{const data=loadPrivate();if(data)applyAccount(data);});
}
